name: Surge PR Preview

on: [ pull_request_target, push ]

jobs:
  preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build
        run: |
          npx gitbook-cli@2.3.2 install
          npx gitbook-cli@2.3.2 build . ./public
      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build: |
            echo donothing
          dist: docs/public
